### ISSUE TITLE
sync with desktop

### ISSUE THREAD

**Issue by jeyca** [xorum-io/open_money_tracker#15]
is there any way, to sync the data with desktop? I know I can export/import data, but is there a file I can sync using adb or ssh to my phone? How/where is the data stored?

**Comment by yevhenii-kanivets** [comment]
Hi @jeyca, data is stored in SQL database, which you can sync to Dropbox, and then copy it to your desktop from Dropbox. SQL database can be read and written with many different programs.

**Comment by jeyca** [comment]
I guess its a sqlite database? but where is it stored exactly? I cant even find a folder for this app in `/storage/emulated/0/Android/data`

**Comment by yevhenii-kanivets** [comment]
This should be `/data/data/com.blogspot.e_kanivets.moneytracker`.
