### ISSUE TITLE
Information about accounts is not exported when using import/export

### ISSUE THREAD

**Issue by whereismybugfix** [xorum-io/open_money_tracker#20]
## Description
Recently I needed to replace my mobile phone and to export all the existing data from the app using "Import/Export" feature in the app menu. It created a file with all the data that I transferred to another device. After transfer I noticed that all the data about existing accounts disappeared. It seems that exported file didn't contain that information too. In order to restore the info about accounts I had to enter it manually afterwords, but all the past transactions lost the value of that field anyway and I observe "Account removed" in the account field.

## Solution
Put all the accounts information into exported file, so that there's a feature to import it from file on the other end.

**Comment by yev-kanivets** [comment]
Hi @whereismybugfix, thanks for reporting the issue! Actually, for the sync between devices (old and new one), there is a Dropbox sync feature, which you can use. It takes all the database and makes backups of it, which then can be restored on any device.

As for the import/export feature, it was developed for moving the data between OMT and other applications.

Let me know if it answers your request 🙏

**Comment by whereismybugfix** [comment]
Hello @yev-kanivets. It actually does. Thank you! The only potential issue here is that if the person doesn't have Dropbox account, there's no way to move DB-file. The feature to export/import whole DB-file would be cool.

**Comment by yev-kanivets** [comment]
@whereismybugfix I'm happy it helped in your case! Exporting/importing these sensitive files isn't that simple on Android, but I'll keep in mind if ever we have a bandwidth for it.
