### ISSUE TITLE
Info about app update

### ISSUE THREAD

**Issue by kasamdor** [xorum-io/open_money_tracker#31]
Replace the substring "4pda.ru" with "4pda.to" because 4pda ru-domain are blocked in Russia by court of law.
https://github.com/xorum-io/open_money_tracker/blob/b4aa4597a1070ae712ef2b584717cbf2547bab5c/app/src/main/res/values-ru/strings.xml#L108
Maybe it's worth to replace the substring "ru.wikipedia.org/wiki/GNU_General_Public_License#GPL_v3" with "en.wikipedia.org/wiki/GNU_General_Public_License"?
https://github.com/xorum-io/open_money_tracker/blob/b4aa4597a1070ae712ef2b584717cbf2547bab5c/app/src/main/res/values/strings.xml#L118

**Comment by yev-kanivets** [comment]
@kasamdor thanks, you are right. I've updated a few more links in all translations.
