### ISSUE TITLE
A display bug

### ISSUE THREAD

**Issue by franklinbill** [xorum-io/open_money_tracker#7]
Dear developer
In the process of using, I found a bug in layout / display. As shown in the figure, In the red box, the text is not fully displayed.
App version is 1.2, my mobile phone is Google nexus 6, screen resolution setting is 1440 * 2560, font size is the largest, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
![image](https://user-images.githubusercontent.com/18572115/91206797-5053a580-e73a-11ea-8e5e-dd18f98b522d.png)

**Comment by yevhenii-kanivets** [comment]
@franklinbill should be fixed by https://github.com/xorum-io/open_money_tracker/commit/8ee38988a2f7259b99a7a5b6b54795494b592c8d

**Comment by franklinbill** [comment]
Thanks*1000000 for your reply! I think it's a good way to fix it.
